// <auto-generated />
using LoyaltyPlatform.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoyaltyPlatform.EntityFramework.Migrations
{
    [DbContext(typeof(DbLoyaltyPlatformContext))]
    partial class DbLoyaltyPlatformContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoyaltyPlatform.EntityFramework.EntityModel.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FlagIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePrefixNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("LoyaltyPlatform.EntityFramework.EntityModel.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("State", (string)null);
                });

            modelBuilder.Entity("LoyaltyPlatform.EntityFramework.EntityModel.State", b =>
                {
                    b.HasOne("LoyaltyPlatform.EntityFramework.EntityModel.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
            modelBuilder.Entity("LoyaltyPlatform.EntityFramework.EntityModel.City", b =>
            {
                b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<String>("Name")
                .IsRequired()
                .HasColumnType("nvarchar(max)");
                b.Property<int>("CountryId")
                       .HasColumnType("int");
                b.Property<int>("StateId")
                        .HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("CountryId");
                b.HasIndex("StateId");
                b.ToTable("City", (string)null);
            });
            modelBuilder.Entity("LoyaltyPlatform.EntityFramework.EntityModel.City", b =>
            {
                b.HasOne("LoyaltyPlatform.EntityFramework.EntityModel.Country", "Country")
                    .WithMany()
                    .HasForeignKey("CountryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Country");
            });
            modelBuilder.Entity("LoyaltyPlatform.EntityFramework.EntityModel.City", b =>
            {
                b.HasOne("LoyaltyPlatform.EntityFramework.EntityModel.State", "State")
                    .WithMany()
                    .HasForeignKey("StateId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("State");
            });
            modelBuilder.Entity("LoyaltyPlatform.EntityFramework.EntityModel.Township", b =>
            {
                b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<String>("Name")
                .IsRequired()
                .HasColumnType("nvarchar(max)");
                b.Property<int>("CityId")
                       .HasColumnType("int");
                b.Property<int>("StateId")
                        .HasColumnType("int");
                b.Property<int>("CountryId")
                       .HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("CityId");
                b.HasIndex("StateId");
                b.HasIndex("CountryId");              
                b.ToTable("Township", (string)null);
            });
            modelBuilder.Entity("LoyaltyPlatform.EntityFramework.EntityModel.Township", b =>
            {
                b.HasOne("LoyaltyPlatform.EntityFramework.EntityModel.City", "City")
                    .WithMany()
                    .HasForeignKey("CityId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("City");
            });
            modelBuilder.Entity("LoyaltyPlatform.EntityFramework.EntityModel.Township", b =>
            {
                b.HasOne("LoyaltyPlatform.EntityFramework.EntityModel.State", "State")
                    .WithMany()
                    .HasForeignKey("StateId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("State");
            });
            modelBuilder.Entity("LoyaltyPlatform.EntityFramework.EntityModel.Township", b =>
            {
                b.HasOne("LoyaltyPlatform.EntityFramework.EntityModel.Country", "Country")
                    .WithMany()
                    .HasForeignKey("CountryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Country");
            });
#pragma warning restore 612, 618
        }
    }
}
